[package]
name = "powdr_revm"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { git = "https://github.com/powdr-labs/revm.git", branch = "no-std", default-features = false }
runtime = { git = "https://github.com/powdr-labs/powdr.git", branch = "main" }
